name: Build and Test Horizons App

on:
  push:
    branches: [ "develop", "feature" ]

jobs:
  build_test:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore
    - name: Execute tests
      run: dotnet test --no-build --verbosity normal
